開発用
shirasu-aq/counter_React_practice pull request #10
Opened 2021-06-03 02:52 UTC by shirasu-aq

2021-06-03 07:51 UTC, shirasu-aq commented
developブランチの方で確認お願いします。

2021-06-03 08:47 UTC, tatsuya-asami requested changes
PR作成時にやるべきことが出来ていないようです。

1. タイトル、本文で何をやったかわかるようにする

これだとわからないので、タイトルには「JavaScriptの実装」など何のPRかがわかるようにしたいです。

本文もどこをレビューすればいいか書いてもらいたいです。今やってる内容だと書きにくいと思いますが、おそらく3つのボタンを動作するようにしたのが今回のPRでの変更内容だと思うので、それだけでも書いてもらいたいです。

レビューして欲しい部分、しないでいい部分もある場合は書きましょう。今回だと色々試したコミットが27つあるけど、それぞれを見てもらいたいわけではないと思います。なので「試したコミットが入っているのでCommitsは見ないで下さい」とかを書くとよいです。

![image](https://user-images.githubusercontent.com/46734354/120615120-e7e8e000-c492-11eb-8eb0-0b83b3419ee9.png)

2. 差分がおかしいので、レビュー依頼する前に確認する。

昨日package.jsonを修正したはずなのにまた差分にあります。これはひと目でわかるので、依頼する前に自分で確認するようにしましょう。
![image](https://user-images.githubusercontent.com/46734354/120615600-66de1880-c493-11eb-9b10-79012c2a1e6c.png)

実装開始時にrebase, レビュー依頼する前にrebase, マージする前にrebaseが必要です。

2021-06-03 09:59 UTC, shirasu-aq commented
> 1. タイトル、本文で何をやったかわかるようにする

確かにその通り、何をして欲しいかわからなくて酷いプルリクだったなと思いました…。
指摘ありがとうございます。

> 2. レビュー依頼する前に確認する。
> 
> 
> 実装開始時にrebase, レビュー依頼する前にrebase, マージする前にrebaseが必要です。

承知しました。癖をつけたいと思います。

2021-06-07 07:55 UTC, shirasu-aq commented
rebaseしてプッシュし直しました。

2021-06-07 08:22 UTC, shirasu-aq commented
Files changedにmainとの差分だけが出るように修正しました。

2021-06-07 08:47 UTC, tatsuya-asami requested changes
IMOのコメントは修正お願いします。nits修正するかどうかはお任せします。

2021-06-07 08:47 UTC, tatsuya-asami commented on src/ButtonActions.js
> +export default ButtonActions;
- nits
この書き方は何も間違ってないですが、default exportはちょっと扱いにくくなるので、named exportにしましょう。
「より限定的な機能を使うようにする」の法則の一つだと思って覚えてしまって大丈夫です。

https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/

40行目を削除して、
```ts
export function ButtonActions()
```
とすればよいです。

import する側では

```ts
import { ButtonActions } from "./ButtonActions";
```
と`{}`で囲めばよいです。

2021-06-07 08:47 UTC, tatsuya-asami commented on src/ButtonActions.js
> +function ButtonActions() {
- nits
間違えではないのですが、アロー関数を使わない理由がないと思うので、全部アロー関数に統一しちゃいましょう。

```ts
const ButtonActions = () => {
```

2021-06-07 08:47 UTC, tatsuya-asami commented on src/ButtonActions.js
> +  const spanColor = count > 0 ? "green" : count < 0 ? "red" : "span";
- IMO
ternary operatorの入れ子は解読が難しいのでやめましょう。


```ts
const selectSpanColor = () => {
  if(count > 0) {
    return 'green'
  } 
  if(count < 0) {
    return 'red'
  }
  return 'span'
}

const spanColor = selectSpanColor()
```
こっちの方が簡単に読めるのがわかると思います。ternary operatorは2択のときだけ特別に使える。くらいの感じで思っていたほうが良いです。

- IMO
命名が規則的でないので規則を揃えましょう。`green`, `red`, `black`なら色だけが違うというのがひと目で分かると思います。

- nits
CSSの方がcolor以外にもパラメーターを持っている場合は、クラス名を色に決めつけないほうが良いです。

たとえば `count > 0` の時に文字のサイズも変えるとしたら
```ts
const selectSpanColor = () => {
  if(count > 0) {
    return 'countPositive'
  } 
  if(count < 0) {
    return 'countNegative'
  }
  return 'countZero'
}
```

```css
.countPositive {
  font-size: 15px;
  color: green;
}

.countNegative {
  font-size: 12px;
  color: red
}

.countZero {
  color: black
}
```

の方が、cssファイルを見た時にもどこのクラスなのかがわかりやすくてよいですね！

2021-06-07 14:58 UTC, shirasu-aq commented on src/ButtonActions.js
アロー関数に書き換え、named exportに変更しました。

2021-06-07 14:58 UTC, shirasu-aq commented on src/index.js
> +import { App } from "./App";
App.jsの方も同じようにアロー関数に書き換えて、named exportに変更しました。

2021-06-07 14:59 UTC, shirasu-aq commented on src/ButtonActions.js
> +  const spanColor = selectSpanColor();
解読しやすいようにif文に書き換え、クラス名にblackを追加しました。

2021-06-07 15:02 UTC, shirasu-aq commented
レビュー有難うございました。

* IMO
・ternary operatorの入れ子をif文に変更する。
・色変更時の命名をわかりやすくする。

- NITS

・default exportをnamed exportに変更する。
・functionをアロー関数に書き換える。

こちら変更し、再度プッシュしました。確認お願いいたします。

2021-06-07 15:03 UTC, shirasu-aq commented on src/ButtonActions.js
> +  const spanColor = count > 0 ? "green" : count < 0 ? "red" : "span";
命名規則に関してはそうで、今回は色の変更のみだったのでわかりやすく、クラス名を変更後の色にしたのですが、他の要素も変更したい場合、包含的な意味を持ちそうなものにするべきだと思いました。

例に出してくださった```positive```や```negative```はよくクラス名で見る表現だなと思い出しました。

2021-06-08 02:42 UTC, tatsuya-asami commented on src/ButtonActions.js
> +  const spanColor = count > 0 ? "green" : count < 0 ? "red" : "span";
> 例に出してくださったpositiveやnegativeはよくクラス名で見る表現だなと思い出しました。

これはクラス名で頻出な表現ではなく、正の値と負の値を意味する単語として使ってます。

2021-06-08 02:46 UTC, tatsuya-asami commented on src/ButtonActions.js
> +  const spanColor = count > 0 ? "green" : count < 0 ? "red" : "span";
修正報告はこっちでしてもらうとよりわかりやすいです

例えば下記みたいな感じで。そうすればこのconversationもresolve出来て、必要な情報のみが表示され続けます。


・ternary operatorの入れ子をif文に変更する。
・色変更時の命名をわかりやすくする。 

指摘事項修正しました 91e8c89

2021-06-08 02:47 UTC, tatsuya-asami commented on src/ButtonActions.js
https://github.com/shirasu-aq/counter_React_practice/pull/10#discussion_r647070191 と同じです。これに関しては引用しているコードもoutdatedになってしまっています。

![image](https://user-images.githubusercontent.com/46734354/121114779-30b3e680-c84f-11eb-9a4b-2425328b8231.png)

2021-06-08 02:47 UTC, tatsuya-asami commented on src/index.js
> +import { App } from "./App";
#10 (comment) と同じです。

2021-06-08 02:47 UTC, tatsuya-asami commented on src/ButtonActions.js
> +  const spanColor = selectSpanColor();
#10 (comment) と同じです。

2021-06-08 02:51 UTC, tatsuya-asami approved these changes
段々と出来ることは増えてきましたが、まだgithubの使い方改善点が多いので、この点の改善は頑張ってみて下さい。

今回はソースコードをより良く書く指摘もしてみましたが、githubの使い方が改善されていけばもっとそっちの指摘ができるようになります！

2021-06-08 06:07 UTC, merged